### ISSUE TITLE
seperate backlog column

### ISSUE THREAD

**Issue by vistree** [kanboard/forum#106]
Hi, I really like this tool ;-) I'm missing just one really important function: a separate backlog column for projects with swimlanes. Normally you define tasks in a backlog refinement and - when starting work for a sprint - you fill your swimlanes. I know there is the suggestion to use a separate project for backlogs - but then I have to duplicate ALL my project to define the backlog tasks which will make the whole kanboard really hard to use. Any way to get this as a feature?

**Comment by creecros** [comment]
Can you explain better? It's not making sense to me.

**Comment by vistree** [comment]
Hi creecros,
thanx for coming back to my feature request. What I want is a single column for backlog tasks wich spans the full height of the board and is NOT splittet by swimlanes. I tried to create an example layout which is attached below. Does this make more sense then my initial description? Hope so ;-)
![board-with-backlog-column](https://user-images.githubusercontent.com/7022827/45942482-ddd46b00-bfe2-11e8-8655-4cbfde066a1a.png)

**Comment by creecros** [comment]
i suck at html, but suck even worse at tables in html. I can point you in the right direction though.

[The Templates you need to look at can be found here](https://github.com/kanboard/kanboard/tree/master/app/Template/board)

[This template seems to build the board](https://github.com/kanboard/kanboard/blob/master/app/Template/board/table_container.php)

[This template is writing the HTML for the swimlanes](https://github.com/kanboard/kanboard/blob/master/app/Template/board/table_swimlane.php)

My guess is, you'd have to sacrifice some collapsible features to make it work though. If you can figure out the HTML, It'll be easy to turn into a plugin.

**Comment by vistree** [comment]
Hi creecros,
I had a deeper look now and were able to find 2 possible solutions: first is to modifiy the table_container.php file. I put the output as a link to this topic. To test you have to rename the file extension from txt to php. Then create a board and name the first (!) swimlane "backlog" and the first (!) column also "backlog". Rename the existing file /app/Template/board/table_column.php e.g. to table_column.php.bak and use my template instead.
[table_container.txt](https://github.com/kanboard/forum/files/2455590/table_container.txt)

Most works. Only problem is, that this way the column collapsing does not fully work for the main region (columns NOT being backlog) and not working at all for my new column backlog. Reason is, that to render everything smooth I needed to put 2 tables in 2 table-tds. Do you have an idea how to solve this?

Second approach is to modify the template file table_tasks.php and table_columns.php
What I tried is to remove the backlog column from all swimlanes except the first one (in the table_columns.php) and add rowspan=X to the first td. X is the number of swimlanes * 3 -2
Here the whole table looks nasty afterwards and collapsing the backlog column results in extra and shifted buttons in all swimlanes. Seems to be more effort to make this cleanly work then with the first solution. What do you think?

**Comment by vistree** [comment]
You can find a similar discussion in the[ kanboard issue lane](https://github.com/kanboard/kanboard/issues/3547).

**Comment by creecros** [comment]
I can take a look next chance I get. What's your end goal? A plugin?

**Comment by vistree** [comment]
Hi again ;-) as there are several similar requests on the kanboard issue section I think a plugin would be good. So others could also use this (as reference).

**Comment by creecros** [comment]
Make a repo and add me. That way you can maintain it after I done.

**Comment by vistree** [comment]
We will continue diskussion in the new repro: https://github.com/vistree/kanboard-backlog
