### ISSUE TITLE
Import group

### ISSUE THREAD

**Issue by patricej** [kanboard/forum#108]
Hello!

Is there a way to import a group name for each user in the .csv ? 
Now, I need to add the users one by one in my groups... and it's a long time !

Patrice

**Comment by creecros** [comment]
No.

You could use an LDAP server as an alternative.

**Comment by creecros** [comment]
Another alternative would be to edit the user table directly, if there is alot, might be easier with something like phpmyadmin.

**Comment by patricej** [comment]
OK, I'll try with phpmyadmin... Thank you !
