### ISSUE TITLE
No plugin installation with docker hosted kanboard

### ISSUE THREAD

**Issue by solick** [kanboard/forum#113]
Hi, i installed a fresh kanboard via docker and linked it to a mysql docker instance. data and plugin are outside defined.

Everything work fine but i am not able to install plugins via the website.

Write access to folder is given, define in config.php set. I havn´t checked it the docker version supports the zip extension because i expect them to do so.

Any ideas how to solve this issue?

**Comment by creecros** [comment]
I use docker. Everything works fine. With no other info, can't help you beyond that.

**Comment by solick** [comment]
Hi,

docker-compose part:

    kanboard:
        image: kanboard/kanboard:latest
        container_name: kanboard
        networks:
         - kanboard-backend
        ports:
         - 10180:80
         - 10101:443
        volumes:
         - /volume1/docker/kanboard/data:/var/www/app/data
         - /volume1/docker/kanboard/plugins:/var/www/app/plugins
         - /volume1/docker/kanboard/ssl:/etc/nginx/ssl
       restart: always


      mysql_kanboard:
        image: mysql:5.7.23
        container_name: mysql_kanboard
        networks:
           - kanboard-backend
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --skip-character-set-client-handshake --lower-case-table-names=2
        ports:
           - 3309:3306
        environment:
           - MYSQL_ROOT_PASSWORD=XXX
           - MYSQL_ROOT_HOST=%
           - LOWER_CASE_TABLE_NAMES=2
        volumes:
           - /volume1/docker/mysql_kanboard/var/lib/mysql:/var/lib/mysql
           - /volume1/docker/mysql_kanboard/var/log/mysql:/var/log/mysql
           - /volume1/docker/mysql_kanboard/mysql/mysql-conf.d:/etc/mysql/mysql-conf.d
        restart: always

Mysql connection works.

What other info do you expect?

**Comment by creecros** [comment]
First thing I notice.

Don't use kanboard:latest

**Comment by creecros** [comment]
Also, the dockers image comes with sqlite...so you don't really need the mysql. But if your intent on using it, up to you.

**Comment by creecros** [comment]
And just for curiosity, your not using rancher,  are you?

**Comment by solick** [comment]
> First thing I notice.
> 
> Don't use kanboard:latest

Lokking at the official documentation, the example docker-compose file also use the latest tag.

**Comment by solick** [comment]
> And just for curiosity, your not using rancher, are you?

not that i know: It is the synology docker daemon

**Comment by creecros** [comment]
Either way, sounds like a permissions thing. Try binding to mnt folder instead, or a volume.

**Comment by solick** [comment]
So i tried a couple of things:
1. checked if the plugin dir is visible (by logging into the docker container). I can see the dir and also files within the dir.
2. Try to install manually 2 plugins (Gantt, Mattermost) but also this fails.

**Comment by solick** [comment]
> Are there files in the plug in dir, both inside and outside the container?

Yes. 
I installed the exact same config on a normal ubuntu and there it works perfectly. Seems to have something to do with the synology environment where the first installation is located

**Comment by solick** [comment]
Finally i found out:

Because plugin folder is parent level of data folder, the config has to be adjusted like this:

    define('PLUGINS_DIR', __DIR__.DIRECTORY_SEPARATOR.'/../plugins');

Now it works!

**Comment by creecros** [comment]
Glad you figured it out, sorry I wasn't more help
