### ISSUE TITLE
Disabled Gantt with visitor

### ISSUE THREAD

**Issue by tjdm007** [kanboard/forum#120]
Hello,

On the last release of KanBoard, is it possible to disabled Gantt function when visitor is connected.
This profil can move and change dates !!! 
Can you help us?
Thank you.

**Comment by creecros** [comment]
FYI, it's not a Kanboard version issue.

**Comment by tjdm007** [comment]
The author of the plugin is still the same.
Changes, as you indicate, do not work.
Thanks anyway

**Comment by tjdm007** [comment]
The author of the plugin is still the same.
Changes, as you indicate, do not work.
Thanks anyway


Le mar. 6 nov. 2018 à 03:11, Craig Crosby <notifications@github.com> a
écrit :

**Comment by creecros** [comment]
If you add those lines, there isn't a chance that the changes wouldn't work.

Either way, tested and confirmed.

**Comment by tjdm007** [comment]
Do you want to test ?
https://145.239.155.79/kanboard/
login demo / pwd demo01

**Comment by tjdm007** [comment]
plugin.php : 

       $this->route->addRoute('gantt/:project_id', 'TaskGanttController', 'show', 'plugin');
        $this->route->addRoute('gantt/:project_id/sort/:sorting', 'TaskGanttController', 'show', 'plugin');
        
        $this->projectAccessMap->add('ProjectGanttController', 'save', Role::PROJECT_MANAGER);
        $this->projectAccessMap->add('TaskGanttController', 'save', Role::PROJECT_MEMBER);
    
        $this->template->hook->attach('template:project-header:view-switcher', 'Gantt:project_header/views');

**Comment by creecros** [comment]
works as intended, I cannot modify dates via the gantt chart.

**Comment by creecros** [comment]
what is your intent? remove chart completely?

**Comment by tjdm007** [comment]
Your solution with "*" suits me perfectly.
The goal is that a user does not have access to the Gantt.
Your solution is perfect.
You can try.
You are excellent.
Thank you
Thierry (France)

**Comment by creecros** [comment]
Which ever you use, "*" or "save", the viewer won't be able to actually save any changes they make. With "*" they won't even be able to see it.

Your welcome. Please close the issue.

**Comment by tjdm007** [comment]
Votre solution avec "*" me convient parfaitement.
L'objectif est qu'un utilisateur n'est pas accès au Gantt.
Votre solution est parfaite.
Vous pouvez essayer.
Vous etes excellent.
Merci
Thierry (France)
