### ISSUE TITLE
Documentation for pt-BR

### ISSUE THREAD

**Issue by filhocf** [kanboard/forum#54]
@fguillot , can you open a repo for pt-BR documentation? 
Or give me a orietantion about how to do. I want to translate it.

**Comment by fguillot** [comment]
I created this repo: https://github.com/kanboard/documentation-pt

You can now send pull-requests to update the documentation and the result will be visible here once merged: https://docs.kanboard.org/pt/latest/index.html

The file names must keep the English names and the same directory layout. The software used for the documentation is Sphinx with the reStructuredText (RST) markup language.

Have fun!

**Comment by filhocf** [comment]
@fguillot, IMHO, could be a good idea to open issues section for pt documentation. What do you think?

**Comment by fguillot** [comment]
I opened the issue tracker
