### ISSUE TITLE
Inactive users

### ISSUE THREAD

**Issue by uchopy** [kanboard/forum#65]
Hello,
In order to have tracking of old task, we don't delete user accounts, we just "inactivate" them.
But, the thing is, that in order to add a user to a group, in the dropdown menu, ALL users, even the inactive show up, making the joinning process a bit annoying.

Can we have a workaround such that, inactive users are blocked from groups and don't display on the dropdown menu of groups?

thanks!

**Comment by fguillot** [comment]
this issue has been fixed in the development version.
