### ISSUE TITLE
Problems with cronjob and plugins

### ISSUE THREAD

**Issue by cvanschalkwyk** [kanboard/forum#70]
I am hoping someone can help me here. I am not an experienced programmer, but I have self installed Kanboard and running it since last year successfully (Windows IIS, PHP V7.1, Kanboard v 1.2.4). My cronjob is running successfully for built-in automatic actions, but not for plugins.

In my task scheduler that is running, this is in my batch file:
_"C:\Program Files\PHP\v7.1\php.exe" -f "C:\inetpub\wwwroot\kanboard\cli" cronjob_
As mentioned, all default actions run, but no plugins (yes they are setup correctly and I checked the permissions)

After days of struggling, I found that if I go into cmd and run this from the kanboard folder manually, my plugins are running successfully:
_C:\inetpub\wwwroot\kanboard>php cli cronjob_

What is the difference? how can I get this to work in my batch file?

**Comment by creecros** [comment]
windows...clueless

may help. kanboard/kanboard#2512

**Comment by cvanschalkwyk** [comment]
Thanks I'll try that - have been searching endlessly and never came across that thread. Changed it today to run the command directly from task scheduler out the kanboard folder and it seemed to work. Should probably just move my batch file to the kanboard root folder.
