### ISSUE TITLE
Question/Error after MySQL 2 SQLite Migration

### ISSUE THREAD

**Issue by TheRojam** [kanboard/forum#81]
I previsously migrated my kanboard from mysql to sqlite and now i want to get on this board, but it thoughs an error:
> Internal Error: Unable to run SQL migrations: Running migration \Schema\version_1, SQLSTATE[HY000]: General error: 1 table users already exists (You may have to fix it manually)
I dont now how to do it - hopefully smb can help me

**Comment by joerggollnick** [comment]
I had a slightly different issue while recreating a sqlite3 db from dump.
.dbinfo field "user version" contains current schema version (118 for latest 1.2.5) (this should be in sync with your mysql installation) 
I got the hint from ./cli db:version that worked with old installation and not with new installation.
(The error message means that system like to create an migration from version 0)
It is not a solution for your issue, but may be you can  cheat somehow this field.

**Comment by joerggollnick** [comment]
In my case old version = 115 this would do the trick:
sqlite3> pragma user_version=115;

**Comment by TheRojam** [comment]
thanks i updated to new version via redeployment
