### ISSUE TITLE
Integrate kanboard in my php website

### ISSUE THREAD

**Issue by vaibhavhrt** [kanboard/forum#85]
Any idea how do I integrate kanboard in my existing website so that I can access it as https://mywebsite.com/kanboard/ (which is the easy part).
But I also want users already registered on my website can access kanboard, instead of adding users in kanboard seperately, i.e. kanboard uses the samedb as my website thats used to save user login details.

**Comment by TheCloud** [comment]
You need to implement a new authenticator object that basically 
There are plugins for that: LDAP or Google you can check them out to implement yours
