### ISSUE TITLE
Filter is null when opening a board

### ISSUE THREAD

**Issue by chrisjhowe** [kanboard/forum#95]
Hello, we updated our system to use mysql rather than the sqlite database and copied the sqlite database contents into the new database.  It is all fine apart from the minor irritation that on opening a board the filter value is null.  Clicking reset filter then gives the usual status:open value. 
Where is the default filter value stored?
Thanks
Chris

**Comment by chrisjhowe** [comment]
For all the existing users, for new users it seems to work OK.

I only found out this yesterday so my plan was to look at the users table to see if I could see any differences.

Chris

**Comment by creecros** [comment]
Try logging out and back in.

**Comment by chrisjhowe** [comment]
I found the solution to the problem.  In the user profile the Custom Filter setting was NULL.  Deleting the NULL made the board filter default to status:open.
