### ISSUE TITLE
SAML Authentication removed

### ISSUE THREAD

**Issue by TheElbenreich** [kanboard/forum#96]
Hello,

I have the [SAML authentication plugin](https://github.com/trajche/SamlAuth) installed. However, I saw that it was removed from the plugin directory.

Is there a reason for it?

Best Regards,
Jan

**Comment by fguillot** [comment]
This plugin has never been part of the directory. You can check the plugin directory content and history here: https://github.com/kanboard/website

**Comment by TheElbenreich** [comment]
Oh ok... for some reason it was in my mind that it was in the plugin directory - but then that is not the case.
